(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const Z=["鼠","牛","虎","兔","龍","蛇","馬","羊","猴","雞","狗","豬"];
const T=["子時","丑時","寅時","卯時","辰時","巳時","午時","未時","申時","酉時","戌時","亥時","吉時"];
const LM=["正月","二月","三月","四月","五月","六月","七月","八月","九月","十月","冬月","臘月"];
const LD=["初一","初二","初三","初四","初五","初六","初七","初八","初九","初十","十一","十二","十三","十四","十五","十六","十七","十八","十九","二十","廿一","廿二","廿三","廿四","廿五","廿六","廿七","廿八","廿九","三十"];
const RN={lamp:"七星元辰燈",dou:"祈安禮斗",gaiji:"祭改"}, RP={lamp:200,dou:1200,gaiji:200};
let S={mode:null,people:[],editing:null,cal:null,time:null,zodiac:null,att:null,rituals:new Set()};
const money=n=>"NT$"+n.toLocaleString("zh-TW");
function page(id,n){$$(".page").forEach(x=>x.classList.remove("on"));$("#"+id).classList.add("on");$$(".progress span").forEach((x,i)=>x.classList.toggle("on",i+1===n));window.scrollTo(0,0)}
function choose(selector,el){$$(selector).forEach(x=>x.classList.toggle("selected",x===el))}
function lunarFromSolar(v){try{const d=new Date(v+"T12:00:00"),roc=d.getFullYear()-1911,p=new Intl.DateTimeFormat("zh-TW-u-ca-chinese",{month:"long",day:"numeric"}).formatToParts(d);let m=(p.find(x=>x.type==="month")||{}).value||"";let day=(p.find(x=>x.type==="day")||{}).value||"";m=m.replace("十一月","冬月").replace("十二月","臘月").replace("一月","正月");if(!m.endsWith("月"))m+="月";const num=parseInt(day,10);if(!isNaN(num))day=LD[num-1]||day;return {roc,month:m,day,display:`民國${roc}年 農曆${m}${day}`}}catch(e){return null}}
function birth(){if(S.cal==="solar"){if(!$("#solar").value)return null;return lunarFromSolar($("#solar").value)}if(S.cal==="lunar"){const roc=parseInt($("#roc").value,10),m=$("#lm").value,d=$("#ld").value;if(!roc||!m||!d)return null;return {roc,month:m,day:d,display:`民國${roc}年 農曆${m}${d}`}}return null}
function reset(p=null){$("#name").value=p?p.name:"";$("#addr").value=p?p.addr:"";$("#solar").value="";$("#roc").value="";$("#lm").value="";$("#ld").value="";S.cal=null;S.time=p?p.time:null;S.zodiac=p?p.zodiac:null;S.att=p?p.att:null;S.rituals=new Set(p?p.rituals:[]);if(p&&p.birth){S.cal=p.sourceCal||"lunar";if(S.cal==="solar")$("#solar").value=p.sourceSolar||"";else{$("#roc").value=p.birth.roc;$("#lm").value=p.birth.month;$("#ld").value=p.birth.day}}$$(".cal").forEach(x=>x.classList.toggle("selected",x.dataset.cal===S.cal));$("#solarBox").classList.toggle("hide",S.cal!=="solar");$("#lunarBox").classList.toggle("hide",S.cal!=="lunar");$("#times").querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x.textContent===S.time));$("#zodiacs").querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x.textContent===S.zodiac));$$(".ritual").forEach(x=>x.classList.toggle("selected",S.rituals.has(x.dataset.r)));$("#attBox").classList.toggle("hide",!S.rituals.has("gaiji"));$$(".att").forEach(x=>x.classList.toggle("selected",x.dataset.att===S.att));$("#cloth").classList.toggle("hide",S.att!=="no");$("#err").classList.add("hide");calc()}
function calc(){$("#ptotal").textContent=money(Array.from(S.rituals).reduce((a,r)=>a+RP[r],0))}
function validate(){const miss=[];if(!$("#name").value.trim())miss.push("姓名");if(!birth())miss.push("生辰");if(!S.time)miss.push("時辰／吉時");if(!S.zodiac)miss.push("生肖");if(!$("#addr").value.trim())miss.push("地址");if(!S.rituals.size)miss.push("科儀");if(S.rituals.has("gaiji")&&!S.att)miss.push("祭改是否到場");if(miss.length){$("#err").textContent="⚠️ 尚未完成："+miss.join("、");$("#err").classList.remove("hide");return false}return true}
function person(){return{name:$("#name").value.trim(),addr:$("#addr").value.trim(),birth:birth(),sourceCal:S.cal,sourceSolar:$("#solar").value,time:S.time,zodiac:S.zodiac,att:S.rituals.has("gaiji")?S.att:null,rituals:Array.from(S.rituals),total:Array.from(S.rituals).reduce((a,r)=>a+RP[r],0)}}
function plist(){$("#plist").innerHTML=S.people.map((p,i)=>`<div class="person"><b>${i+1}. ${p.name}</b>　${money(p.total)}<div class="chips">${p.rituals.map(r=>`<span class="chip">${RN[r]}</span>`).join("")}</div><button class="secondary edit" data-i="${i}">修改</button><button class="secondary del" data-i="${i}">刪除</button></div>`).join("");$$(".edit").forEach(b=>b.onclick=()=>{S.editing=+b.dataset.i;reset(S.people[S.editing]);page("s2",2)});$$(".del").forEach(b=>b.onclick=()=>{S.people.splice(+b.dataset.i,1);plist()})}
function summary(){$("#summary").innerHTML=S.people.map((p,i)=>`<div class="sum"><b>${i+1}. ${p.name}</b><br>${p.birth.display}・${p.time}・生肖${p.zodiac}<br>${p.addr}<div class="chips">${p.rituals.map(r=>`<span class="chip">${RN[r]} ${money(RP[r])}</span>`).join("")}</div>${p.att==="no"?'<div class="warn">祭改不克到場：需提前準備本人衣物。</div>':""}</div>`).join("");$("#grand").textContent=money(S.people.reduce((a,p)=>a+p.total,0))}
function slip(){$("#slip").innerHTML=`<h3>混元九龍太子聖誕祈福科儀<br>報名確認單</h3><p style="text-align:center">共 ${S.people.length} 位</p>`+S.people.map((p,i)=>`<div class="slipPerson"><b>${i+1}. ${p.name}</b><br>生辰：${p.birth.display}<br>時辰：${p.time}<br>生肖：${p.zodiac}<br>地址：${p.addr}<br>科儀：${p.rituals.map(r=>RN[r]+" "+money(RP[r])).join("、")}${p.att?`<br>祭改：${p.att==="yes"?"本人會到場":"本人不克到場（需準備衣物）"}`:""}<br><b>小計：${money(p.total)}</b></div>`).join("")+`<h3>應繳總額：${money(S.people.reduce((a,p)=>a+p.total,0))}</h3>`}
function canvas(){const c=document.createElement("canvas"),W=1080,H=Math.max(1000,420+S.people.length*420);c.width=W;c.height=H;const x=c.getContext("2d");x.fillStyle="#fffaf0";x.fillRect(0,0,W,H);x.fillStyle="#681922";x.textAlign="center";x.font="bold 44px sans-serif";x.fillText("混元九龍太子聖誕祈福科儀",W/2,75);x.font="bold 32px sans-serif";x.fillText("報名確認單",W/2,125);x.textAlign="left";let y=190;const draw=(s,size=25,bold=false)=>{x.font=`${bold?"bold ":""}${size}px sans-serif`;x.fillStyle="#2b221e";for(const line of wrap(x,s,W-120)){x.fillText(line,60,y);y+=40}};S.people.forEach((p,i)=>{draw(`${i+1}. ${p.name}`,30,true);draw(`生辰：${p.birth.display}`);draw(`時辰：${p.time}　生肖：${p.zodiac}`);draw(`地址：${p.addr}`);draw(`科儀：${p.rituals.map(r=>RN[r]+" "+money(RP[r])).join("、")}`);if(p.att)draw(`祭改：${p.att==="yes"?"本人會到場":"本人不克到場（需準備衣物）"}`);draw(`小計：${money(p.total)}`,26,true);y+=25});draw(`應繳總額：${money(S.people.reduce((a,p)=>a+p.total,0))}`,34,true);return c}
function wrap(ctx,s,max){const out=[];let l="";for(const ch of s){if(ctx.measureText(l+ch).width>max&&l){out.push(l);l=ch}else l+=ch}if(l)out.push(l);return out}
function blob(){return new Promise((ok,no)=>{try{canvas().toBlob(b=>b?ok(b):no(new Error()),"image/png")}catch(e){no(e)}})}
LM.forEach(m=>$("#lm").insertAdjacentHTML("beforeend",`<option>${m}</option>`));$("#lm").insertAdjacentHTML("afterbegin",'<option value="">農曆月</option>');LD.forEach(d=>$("#ld").insertAdjacentHTML("beforeend",`<option>${d}</option>`));$("#ld").insertAdjacentHTML("afterbegin",'<option value="">農曆日</option>');
T.forEach(t=>{const b=document.createElement("button");b.textContent=t;b.onclick=()=>{S.time=t;choose("#times button",b)};$("#times").appendChild(b)});Z.forEach(z=>{const b=document.createElement("button");b.textContent=z;b.onclick=()=>{S.zodiac=z;choose("#zodiacs button",b)};$("#zodiacs").appendChild(b)});
$$(".mode").forEach(b=>b.onclick=()=>{S.mode=b.dataset.mode;choose(".mode",b);$("#next1").disabled=false;$("#next1").textContent="下一步：填寫資料 →"});
$("#next1").onclick=()=>{S.editing=null;reset();page("s2",2)};
$$(".cal").forEach(b=>b.onclick=()=>{S.cal=b.dataset.cal;choose(".cal",b);$("#solarBox").classList.toggle("hide",S.cal!=="solar");$("#lunarBox").classList.toggle("hide",S.cal!=="lunar")});
$("#solar").onchange=()=>{const b=birth();$("#converted").textContent=b?"✓ "+b.display:"無法轉換，請改用農曆輸入"};
$$(".ritual").forEach(b=>b.onclick=()=>{const r=b.dataset.r;S.rituals.has(r)?S.rituals.delete(r):S.rituals.add(r);b.classList.toggle("selected",S.rituals.has(r));$("#attBox").classList.toggle("hide",!S.rituals.has("gaiji"));calc()});
$$(".att").forEach(b=>b.onclick=()=>{S.att=b.dataset.att;choose(".att",b);$("#cloth").classList.toggle("hide",S.att!=="no")});
$("#savePerson").onclick=()=>{if(!validate())return;const p=person();if(S.editing!==null){S.people[S.editing]=p;S.editing=null}else S.people.push(p);if(S.mode==="single"){summary();page("s3",3)}else{plist();page("people",2)}};
$("#add").onclick=()=>{S.editing=null;reset();page("s2",2)};$("#toConfirm").onclick=()=>{if(!S.people.length)return;summary();page("s3",3)};$("#back").onclick=()=>{if(S.mode==="group"){plist();page("people",2)}else{S.editing=0;reset(S.people[0]);page("s2",2)}};
$("#finish").onclick=()=>{slip();page("s4",4)};
$("#share").onclick=async()=>{try{const b=await blob(),f=new File([b],"混元九龍太子聖誕-報名確認單.png",{type:"image/png"});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]}))){await navigator.share({files:[f],title:"混元九龍太子聖誕報名確認單"})}else throw new Error()}catch(e){if(e&&e.name==="AbortError")return;$("#download").click()}};
$("#download").onclick=async()=>{try{const b=await blob(),u=URL.createObjectURL(b);$("#fallback").innerHTML="";const img=new Image();img.src=u;$("#fallback").appendChild(img);const a=document.createElement("a");a.href=u;a.download="混元九龍太子聖誕-報名確認單.png";a.className="primary";a.style.cssText="display:block;text-align:center;text-decoration:none;margin-top:8px";a.textContent="下載報名單圖片";$("#fallback").appendChild(a)}catch(e){alert("此瀏覽器無法產生圖片，請直接截圖報名確認單。")}};
})();