(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const Z=["鼠","牛","虎","兔","龍","蛇","馬","羊","猴","雞","狗","豬"];
const T=["子時","丑時","寅時","卯時","辰時","巳時","午時","未時","申時","酉時","戌時","亥時","吉時"];
const LM=["正月","二月","三月","四月","五月","六月","七月","八月","九月","十月","冬月","臘月"];
const LD=["初一","初二","初三","初四","初五","初六","初七","初八","初九","初十","十一","十二","十三","十四","十五","十六","十七","十八","十九","二十","廿一","廿二","廿三","廿四","廿五","廿六","廿七","廿八","廿九","三十"];
const names={lamp:"七星元辰燈",dou:"祈安禮斗",gaiji:"祭改"},prices={lamp:200,dou:1200,gaiji:200};
let s={mode:null,people:[],editing:null,calendar:null,time:null,zodiac:null,attendance:null,rituals:new Set()};
const money=n=>"NT$"+Number(n).toLocaleString("zh-TW");
function show(id,step){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$$(".prog").forEach((x,i)=>{x.classList.toggle("active",i+1===step);x.classList.toggle("done",i+1<step)});scrollTo(0,0)}
function selectOnly(selector,el){$$(selector).forEach(x=>x.classList.toggle("selected",x===el))}
function solarToLunar(v){if(!v)return null;try{const d=new Date(v+"T12:00:00");const roc=d.getFullYear()-1911;const p=new Intl.DateTimeFormat("zh-TW-u-ca-chinese",{month:"long",day:"numeric"}).formatToParts(d);let m=(p.find(x=>x.type==="month")||{}).value||"";let day=(p.find(x=>x.type==="day")||{}).value||"";m=m.replace("十一月","冬月").replace("十二月","臘月").replace("一月","正月");if(!m.endsWith("月"))m+="月";const n=parseInt(day,10);if(!isNaN(n))day=LD[n-1]||day;return{roc,month:m,day,display:`民國${roc}年 農曆${m}${day}`}}catch(e){return null}}
function getBirth(){if(s.calendar==="solar"){const v=$("#solarDate").value;const x=solarToLunar(v);return x?{...x,input:"solar",solar:v}:null}if(s.calendar==="lunar"){const roc=parseInt($("#rocYear").value,10),month=$("#lunarMonth").value,day=$("#lunarDay").value;if(!roc||!month||!day)return null;return{roc,month,day,display:`民國${roc}年 農曆${month}${day}`,input:"lunar"}}return null}
function calc(){const t=Array.from(s.rituals).reduce((a,r)=>a+prices[r],0);$("#personTotal").textContent=money(t)}
function clearForm(p=null){$("#name").value=p?.name||"";$("#address").value=p?.address||"";$("#solarDate").value="";$("#rocYear").value="";$("#lunarMonth").value="";$("#lunarDay").value="";s.calendar=p?.birth?.input||null;s.time=p?.time||null;s.zodiac=p?.zodiac||null;s.attendance=p?.attendance||null;s.rituals=new Set(p?.rituals||[]);if(p?.birth?.input==="solar")$("#solarDate").value=p.birth.solar||"";if(p?.birth?.input==="lunar"){$("#rocYear").value=p.birth.roc;$("#lunarMonth").value=p.birth.month;$("#lunarDay").value=p.birth.day}$$(".calendar").forEach(x=>x.classList.toggle("selected",x.dataset.calendar===s.calendar));$("#solarFields").classList.toggle("hidden",s.calendar!=="solar");$("#lunarFields").classList.toggle("hidden",s.calendar!=="lunar");$("#timeGrid").querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x.dataset.value===s.time));$("#zodiacGrid").querySelectorAll("button").forEach(x=>x.classList.toggle("selected",x.dataset.value===s.zodiac));$$(".ritual").forEach(x=>x.classList.toggle("selected",s.rituals.has(x.dataset.ritual)));$("#attendanceFields").classList.toggle("hidden",!s.rituals.has("gaiji"));$$(".attendance").forEach(x=>x.classList.toggle("selected",x.dataset.attendance===s.attendance));$("#clothesWarning").classList.toggle("hidden",s.attendance!=="no");$("#formError").classList.add("hidden");$("#solarConverted").textContent=p?.birth?.input==="solar"&&p.birth.display?"✓ "+p.birth.display:"選擇日期後，系統會自動整理成「民國XX年 農曆X月XX日」。";calc();$("#formHeading").textContent=(s.editing!==null?"修改":"填寫第 "+(s.people.length+1)+" 位")+"資料"}
function validate(){const miss=[];if(!$("#name").value.trim())miss.push("姓名");if(!getBirth())miss.push("生辰");if(!s.time)miss.push("時辰／吉時");if(!s.zodiac)miss.push("生肖");if(!$("#address").value.trim())miss.push("地址");if(!s.rituals.size)miss.push("至少一項科儀");if(s.rituals.has("gaiji")&&!s.attendance)miss.push("祭改是否到場");if(miss.length){$("#formError").textContent="⚠️ 尚未完成："+miss.join("、");$("#formError").classList.remove("hidden");return false}return true}
function collect(){return{name:$("#name").value.trim(),address:$("#address").value.trim(),birth:getBirth(),time:s.time,zodiac:s.zodiac,attendance:s.rituals.has("gaiji")?s.attendance:null,rituals:Array.from(s.rituals),total:Array.from(s.rituals).reduce((a,r)=>a+prices[r],0)}}
function renderPeople(){$("#peopleList").innerHTML=s.people.map((p,i)=>`<div class="personCard"><div class="personHead"><b>${i+1}. ${escapeHtml(p.name)}</b><strong>${money(p.total)}</strong></div><div class="chips">${p.rituals.map(r=>`<span class="chip">${names[r]}</span>`).join("")}</div><div class="miniRow"><button type="button" data-edit="${i}">✏️ 修改</button><button type="button" data-delete="${i}">🗑️ 刪除</button></div></div>`).join("");$$("[data-edit]").forEach(b=>b.onclick=()=>{s.editing=Number(b.dataset.edit);clearForm(s.people[s.editing]);show("step2",2)});$$("[data-delete]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.delete);if(confirm(`確定刪除「${s.people[i].name}」嗎？`)){s.people.splice(i,1);renderPeople();if(!s.people.length){s.editing=null;clearForm();show("step2",2)}}})}
function renderSummary(){$("#summary").innerHTML=s.people.map((p,i)=>`<div class="summaryCard"><b>${i+1}. ${escapeHtml(p.name)}</b><div>${escapeHtml(p.birth.display)}・${p.time}・生肖${p.zodiac}</div><div>${escapeHtml(p.address)}</div><div class="chips">${p.rituals.map(r=>`<span class="chip">${names[r]} ${money(prices[r])}</span>`).join("")}</div>${p.attendance==="no"?'<div class="warning">祭改本人不克到場：需提前準備本人衣物。</div>':""}</div>`).join("");$("#grandTotal").textContent=money(s.people.reduce((a,p)=>a+p.total,0))}
function renderSlip(){$("#slip").innerHTML=`<div class="slipTitle"><h3>混元九龍太子聖誕祈福科儀</h3><b>報名確認單</b><div>共 ${s.people.length} 位</div></div>`+s.people.map((p,i)=>`<div class="slipPerson"><b>${i+1}. ${escapeHtml(p.name)}</b><br>生辰：${escapeHtml(p.birth.display)}<br>時辰：${p.time}<br>生肖：${p.zodiac}<br>地址：${escapeHtml(p.address)}<br>科儀：${p.rituals.map(r=>names[r]+" "+money(prices[r])).join("、")}${p.attendance?`<br>祭改：${p.attendance==="yes"?"本人會到場":"本人不克到場（需準備衣物）"}`:""}<br><b>小計：${money(p.total)}</b></div>`).join("")+`<div class="slipTotal">應繳總額：${money(s.people.reduce((a,p)=>a+p.total,0))}</div><small>※ 祈安禮斗限25人，以官方LINE工作人員確認名額為準。<br>※ 傳送官方LINE並收到確認後，才算完成報名。</small>`}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function wrap(ctx,text,max){const out=[];let line="";for(const ch of text){if(ctx.measureText(line+ch).width>max&&line){out.push(line);line=ch}else line+=ch}if(line)out.push(line);return out}
function makeCanvas(){const W=1080,H=Math.max(1050,420+s.people.length*430),c=document.createElement("canvas");c.width=W;c.height=H;const x=c.getContext("2d");x.fillStyle="#fffaf0";x.fillRect(0,0,W,H);x.strokeStyle="#8a6429";x.lineWidth=5;x.strokeRect(25,25,W-50,H-50);x.textAlign="center";x.fillStyle="#681922";x.font="bold 44px sans-serif";x.fillText("混元九龍太子聖誕祈福科儀",W/2,85);x.font="bold 32px sans-serif";x.fillText("報名確認單",W/2,135);x.textAlign="left";let y=200;const draw=(t,size=25,bold=false)=>{x.font=`${bold?"bold ":""}${size}px sans-serif`;x.fillStyle="#2a221e";wrap(x,t,W-140).forEach(line=>{x.fillText(line,70,y);y+=40})};s.people.forEach((p,i)=>{draw(`${i+1}. ${p.name}`,31,true);draw(`生辰：${p.birth.display}`);draw(`時辰：${p.time}　生肖：${p.zodiac}`);draw(`地址：${p.address}`);draw(`科儀：${p.rituals.map(r=>names[r]+" "+money(prices[r])).join("、")}`);if(p.attendance)draw(`祭改：${p.attendance==="yes"?"本人會到場":"本人不克到場（需準備衣物）"}`);draw(`小計：${money(p.total)}`,26,true);y+=25});draw(`應繳總額：${money(s.people.reduce((a,p)=>a+p.total,0))}`,34,true);return c}
function imageBlob(){return new Promise((resolve,reject)=>{try{makeCanvas().toBlob(b=>b?resolve(b):reject(new Error("blob")),"image/png")}catch(e){reject(e)}})}
LM.forEach(m=>$("#lunarMonth").insertAdjacentHTML("beforeend",`<option value="${m}">${m}</option>`));$("#lunarMonth").insertAdjacentHTML("afterbegin",'<option value="">請選月份</option>');LD.forEach(d=>$("#lunarDay").insertAdjacentHTML("beforeend",`<option value="${d}">${d}</option>`));$("#lunarDay").insertAdjacentHTML("afterbegin",'<option value="">請選日期</option>');
T.forEach(t=>{const b=document.createElement("button");b.type="button";b.dataset.value=t;b.textContent=t;b.onclick=()=>{s.time=t;selectOnly("#timeGrid button",b)};$("#timeGrid").appendChild(b)});Z.forEach(z=>{const b=document.createElement("button");b.type="button";b.dataset.value=z;b.textContent=z;b.onclick=()=>{s.zodiac=z;selectOnly("#zodiacGrid button",b)};$("#zodiacGrid").appendChild(b)});
$$(".modeCard").forEach(b=>b.onclick=()=>{s.mode=b.dataset.mode;selectOnly(".modeCard",b);$("#goForm").disabled=false;$("#goForm").textContent="下一步：填寫資料 →"});
$("#goForm").onclick=()=>{s.editing=null;clearForm();show("step2",2)};
$("#backMode").onclick=()=>show("step1",1);
$$(".calendar").forEach(b=>b.onclick=()=>{s.calendar=b.dataset.calendar;selectOnly(".calendar",b);$("#solarFields").classList.toggle("hidden",s.calendar!=="solar");$("#lunarFields").classList.toggle("hidden",s.calendar!=="lunar")});
$("#solarDate").onchange=()=>{const x=solarToLunar($("#solarDate").value);$("#solarConverted").textContent=x?"✓ "+x.display:"⚠️ 此裝置無法轉換，請改選農曆手動輸入。"};
$$(".ritual").forEach(b=>b.onclick=()=>{const r=b.dataset.ritual;s.rituals.has(r)?s.rituals.delete(r):s.rituals.add(r);b.classList.toggle("selected",s.rituals.has(r));$("#attendanceFields").classList.toggle("hidden",!s.rituals.has("gaiji"));calc()});
$$(".attendance").forEach(b=>b.onclick=()=>{s.attendance=b.dataset.attendance;selectOnly(".attendance",b);$("#clothesWarning").classList.toggle("hidden",s.attendance!=="no")});
$("#savePerson").onclick=()=>{if(!validate())return;const p=collect();if(s.editing!==null){s.people[s.editing]=p;s.editing=null}else s.people.push(p);if(s.mode==="single"){renderSummary();show("step3",3)}else{renderPeople();show("groupList",2)}};
$("#addPerson").onclick=()=>{s.editing=null;clearForm();show("step2",2)};
$("#groupConfirm").onclick=()=>{if(!s.people.length)return;renderSummary();show("step3",3)};
$("#backEdit").onclick=()=>{if(s.mode==="group"){renderPeople();show("groupList",2)}else{s.editing=0;clearForm(s.people[0]);show("step2",2)}};
$("#toShare").onclick=()=>{renderSlip();show("step4",4)};
$("#shareSlip").onclick=async()=>{try{const blob=await imageBlob();const file=new File([blob],"混元九龍太子聖誕-報名確認單.png",{type:"image/png"});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file],title:"混元九龍太子聖誕報名確認單"});}else{throw new Error("share unsupported");}}catch(e){if(e&&e.name==="AbortError")return;$("#saveSlip").click();}};
$("#saveSlip").onclick=async()=>{try{const blob=await imageBlob(),url=URL.createObjectURL(blob);$("#fallback").classList.remove("hidden");$("#fallback").innerHTML="";const img=new Image();img.src=url;img.alt="報名確認單圖片";$("#fallback").appendChild(img);const a=document.createElement("a");a.href=url;a.download="混元九龍太子聖誕-報名確認單.png";a.className="btn primary";a.textContent="⬇️ 下載／儲存報名單圖片";$("#fallback").appendChild(a);$("#fallback").scrollIntoView({behavior:"smooth"})}catch(e){alert("此瀏覽器無法產生圖片，請直接截圖畫面中的報名確認單。")}};
})();