const $=id=>document.getElementById(id), rituals=[...document.querySelectorAll('.ritual')];
const zodiacs=['🐭 鼠','🐮 牛','🐯 虎','🐰 兔','🐲 龍','🐍 蛇','🐴 馬','🐐 羊','🐵 猴','🐔 雞','🐶 狗','🐷 豬'];
document.querySelectorAll('.zodiac').forEach(box=>{zodiacs.forEach(z=>{const b=document.createElement('button');b.type='button';b.textContent=z;b.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(box.dataset.target).value=z.replace(/^\S+\s/,'');update()};box.appendChild(b)})});
function selected(){return rituals.filter(x=>x.checked)} function money(n){return Number(n).toLocaleString('zh-TW')}
function update(){rituals.forEach(r=>$(r.dataset.key+'Fields').classList.toggle('show',r.checked));let total=selected().reduce((s,r)=>s+Number(r.dataset.price),0);$('total').textContent='NT$ '+money(total);let a=[];selected().forEach(r=>a.push(`<b>${r.dataset.name}</b>　NT$${money(r.dataset.price)}`));$('summary').innerHTML=a.length?a.join('<br><br>'):'請先填寫資料並選擇科儀。'}
rituals.forEach(r=>r.addEventListener('change',update));document.querySelectorAll('input,textarea').forEach(x=>x.addEventListener('input',update));
document.querySelectorAll('.presence button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.presence button').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('presence').value=b.dataset.value;$('clothes').classList.toggle('show',b.dataset.value.includes('不克'))});
function val(id){return $(id).value.trim()} function row(k,v){return `<div class="rrow"><span>${k}</span><strong>${v||'未填'}</strong></div>`}
function validate(){let e=[];if(!val('name'))e.push('請填寫報名人姓名');if(!val('phone'))e.push('請填寫聯絡電話');if(!selected().length)e.push('請至少選擇一項科儀');if($('.ritual[data-key="lamp"]').checked){if(!val('lampBirth')||!val('lampAddress')||!val('lampZodiac'))e.push('請完整填寫七星元辰燈資料')}if($('.ritual[data-key="dou"]').checked){if(!val('douBirth')||!val('douAddress'))e.push('請完整填寫祈安禮斗資料')}if($('.ritual[data-key="gaigai"]').checked){if(!val('gaigaiBirth')||!val('gaigaiZodiac')||!val('presence'))e.push('請完整填寫祭改資料')}return e}
$('form').addEventListener('submit',e=>{e.preventDefault();const errs=validate();$('error').innerHTML=errs.join('<br>');if(errs.length){$('error').scrollIntoView({behavior:'smooth',block:'center'});return}let html=`<section class="person"><h3>報名人資料</h3>${row('姓名',val('name'))}${row('聯絡電話',val('phone'))}${val('lineName')?row('LINE名稱',val('lineName')):''}</section>`;let no=0,total=0;selected().forEach(r=>{no++;total+=Number(r.dataset.price);html+=`<section class="ritualBlock"><div class="ritualTitle"><b>${no}. ${r.dataset.name}</b><strong>NT$${money(r.dataset.price)}</strong></div>`;if(r.dataset.key==='lamp')html+=row('生辰',val('lampBirth'))+row('地址',val('lampAddress'))+row('生肖',val('lampZodiac'));if(r.dataset.key==='dou')html+=row('生辰',val('douBirth'))+row('地址',val('douAddress'))+`<div class="quota">限25人｜名額以官方 LINE 回覆確認為準</div>`;if(r.dataset.key==='gaigai'){html+=row('生辰',val('gaigaiBirth'))+row('生肖',val('gaigaiZodiac'))+row('本人到場',val('presence'));if(val('presence').includes('不克'))html+=`<div class="clothesReceipt">⚠️ 未到場者請準備本人衣物，提前放置宮廟。</div>`}html+='</section>'});if(val('note'))html+=`<section class="person"><h3>其他備註</h3><p>${val('note').replace(/</g,'&lt;')}</p></section>`;$('receiptBody').innerHTML=html;$('receiptTotal').textContent='NT$ '+money(total);$('receiptModal').classList.add('show');$('receiptModal').setAttribute('aria-hidden','false');document.body.classList.add('locked');$('receipt').scrollIntoView({block:'start'})});
function close(){ $('receiptModal').classList.remove('show');$('receiptModal').setAttribute('aria-hidden','true');document.body.classList.remove('locked')}$('closeModal').onclick=close;$('backEdit').onclick=close;update();
